name: project5
description: A Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  location: ^4.3.0
  image_picker: ^0.8.4+10
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  intl: ^0.17.0
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
